### ISSUE TITLE
expressworks won't start

### ISSUE THREAD

**Issue by anupamkumar** [nodeschool/nodeschool.github.io#249]
I installed expressworks via npm 

`npm install -g expressworks` and ran `expressworks`, selected the first exercise, but it fails.

This is the error.
`
    Error: Cannot find module 'workshopper-exercise'

    at Function.Module._resolveFilename (module.js:338:15)

    at Function.Module._load (module.js:280:25)

    at Module.require (module.js:364:17)

    at require (module.js:380:17)

    at Object.<anonymous> (/usr/lib/node_modules/expressworks/exercises/hello_world/exercise.js:3:21)

    at Module._compile (module.js:456:26)

    at Object.Module._extensions..js (module.js:474:10)

    at Module.load (module.js:356:32)

    at Function.Module._load (module.js:312:12)

    at Module.require (module.js:364:17)
`

**Comment by SomeoneWeird** [comment]
This should be resolved, I think. Open another issue on the discussions repo if you're still having trouble.
